const VIEW_USER = "VIEW_USER";
const DELETE_USER = "DELETE_USER";
const UPDATE_USER = "UPDATE_USER";
const CREATE_USER = "CREATE_USER";
const EDIT_MATERIAL = 'EDIT_MATERIAL';
const DELETE_MATERIAL = "DELETE_MATERIAL";
const VIEW_MATERIAL = "VIEW_MATERIAL";
export const ModalType = {
    VIEW_USER, DELETE_USER, UPDATE_USER, CREATE_USER, EDIT_MATERIAL, DELETE_MATERIAL, VIEW_MATERIAL

}