const VIEW_USER = "VIEW_USER";
const DELETE_USER = "DELETE_USER";
const UPDATE_USER = "UPDATE_USER";
const CREATE_USER = "CREATE_USER";

export const ModalType = {
    VIEW_USER, DELETE_USER, UPDATE_USER, CREATE_USER
}