const VIEW_USER = "VIEW_USER";
const DELETE_USER = "DELETE_USER";
const UPDATE_USER = "UPDATE_USER";
const CREATE_USER = "CREATE_USER";
const EDIT_MATERIAL = "EDIT_MATERIAL";
const DELETE_MATERIAL = "DELETE_MATERIAL";
const VIEW_MATERIAL = "VIEW_MATERIAL";
const DELETE_CATEGORY = "DELETE_CATEGORY";
const EDIT_CATEGORY = "EDIT_CATEGORY";
const VIEW_CATEGORY = "VIEW_CATEGORY";
const DELETE_SUPPLIER = "DELETE_SUPPLIER";
const EDIT_SUPPLIER = "EDIT_SUPPLIER";
const VIEW_SUPPLIER = "VIEW_SUPPLIER";
const VIEW_WAREHOUSE = "VIEW_WAREHOUSE";
const DELETE_WAREHOUSE = "DELETE_WAREHOUSE";
const EDIT_WAREHOUSE = "EDIT_WAREHOUSE";
export const ModalType = {
  VIEW_USER,
  DELETE_USER,
  UPDATE_USER,
  CREATE_USER,
  EDIT_MATERIAL,
  DELETE_MATERIAL,
  VIEW_MATERIAL,
  DELETE_CATEGORY,
  EDIT_CATEGORY,
  VIEW_CATEGORY,
  DELETE_SUPPLIER,
  EDIT_SUPPLIER,
  VIEW_SUPPLIER,
  VIEW_WAREHOUSE,
  DELETE_WAREHOUSE,
  EDIT_WAREHOUSE
};
