const USER = 'USER'
const ROLE = 'ROLE'
const TYPE = 'TYPE'
const CATEGORY = 'CATEGORY'
const MATERIAL = 'MATERIAL'
const ACCOUNT_INFO = 'ACCOUNT_INFO'
const USER_MANAGEMENT = 'USER_MANAGEMENT'
const MATERIAL_MANAGEMENT = 'MATERIAL_MANAGEMENT'
const DASHBOARD = 'DASHBOARD'
const USER_INFOMATION = 'USER_INFOMATION'
export const RouteType = {
    USER, ROLE, TYPE, CATEGORY, MATERIAL, ACCOUNT_INFO, USER_MANAGEMENT, MATERIAL_MANAGEMENT, DASHBOARD, USER_INFOMATION
}